version: '3'
services:
  portfolio-app:
    image: react/portfolio
    container_name: portfolio_frontend
    build:
      context:  ./
    restart: always

networks:
  default:
    external:
      name: nginx-proxy-manager-network