version: '3'
services:
  portfolio-app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"   
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules